#!/bin/bash
 
# Set a trap for SIGINT and SIGTERM signals
trap "echo The program is terminated." SIGTERM SIGINT
 

echo "Press Ctrl+Z stop the process"
 

i=1

################ Main Part #####################
for(;;)
do
  #Print message with counter i
  echo “running the loop for $i times”
  #Increment the counter by one
  ((i++))
done
